version: "3.5"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/certs:/etc/certs
      - ./nginx:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
    links:
      - web
  web:
    container_name: dockerdev
    restart: on-failure
    build: ./
    #      context: ./..
    #      dockerfile: Dockerfile
    #    env_file: ./../.env
    ports:
      - "5000:5000"
    environment:
      PORT: "5000"
      DATABASE_URL: "postgres://goland:goland@db:5432/goland"
    depends_on:
      - db
  db:
    container_name: dockerdev-db
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: goland
      POSTGRES_PASSWORD: goland
      POSTGRES_DB: goland
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql